apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-service
  labels:
    app: guestbook-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook-service
  template:
    metadata:
      labels:
        app: guestbook-service
    spec:
      containers:                
        - name: guestbook-service
          image: gcr.io/google_samples/gb-frontend:v5
          ports:
            - containerPort: 8100
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-service
  labels:
    app: guestbook-service
spec:
  type: NodePort
  selector:
    app: guestbook-service
  ports:
    - nodePort: 31479
      port: 8080
      targetPort: 8300
